import random

# List of lambda functions generating words
word_generators = [
    lambda x: x.upper(),
    lambda x: x.lower(),
    lambda x: x.capitalize(),
    lambda x: x[::-1]
]

def generate_word():
    # Select a random word generator
    word_generator = random.choice(word_generators)
    # Get user input
    user_input = input("Enter a word: ")
    # Generate a word using the selected lambda function
    generated_word = word_generator(user_input)
    return generated_word

def play_game():
    target_word = generate_word()
    print("Guess the word generated by the lambda function!")
    guess = input("Enter your guess: ")
    if guess == target_word:
        print("Congratulations! You guessed the word correctly.")
    else:
        print(f"Sorry, the correct word was: {target_word}")

def main():
    print("Welcome to the Lambda Word Guessing Game!")
    play_game()
    play_again = input("Do you want to play again? (yes/no): ").strip().lower()
    while play_again == 'yes':
        play_game()
        play_again = input("Do you want to play again? (yes/no): ").strip().lower()
    print("Thanks for playing!")

if __name__ == "__main__":
    main()
